services:
  - type: web
    name: toptrack-frontend
    runtime: static
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        headers:
          X-Frame-Options: DENY
          X-Content-Type-Options: nosniff
          Referrer-Policy: strict-origin-when-cross-origin
    envVars:
      - key: REACT_APP_API_URL
        value: https://toptrack.onrender.com
      - key: NODE_ENV
        value: production
    pullRequestPreviewsEnabled: true